/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPredictionMarket,
  IPredictionMarketInterface,
} from "../../ReactivityHook.sol/IPredictionMarket";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "asset_",
        type: "string",
      },
      {
        internalType: "string",
        name: "question_",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "targetPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "createdPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "duration_",
        type: "uint256",
      },
    ],
    name: "createMarket",
    outputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset_",
        type: "string",
      },
    ],
    name: "getActiveMarketId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
    ],
    name: "getMarket",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
      {
        internalType: "string",
        name: "question",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "targetPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "createdPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "yesPool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "noPool",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "resolvedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
      {
        internalType: "enum IPredictionMarket.Side",
        name: "side",
        type: "uint8",
      },
    ],
    name: "placeBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "marketId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "hitTarget",
        type: "bool",
      },
    ],
    name: "resolveMarket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPredictionMarket__factory {
  static readonly abi = _abi;
  static createInterface(): IPredictionMarketInterface {
    return new Interface(_abi) as IPredictionMarketInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPredictionMarket {
    return new Contract(address, _abi, runner) as unknown as IPredictionMarket;
  }
}
