/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SomniaEventHandler,
  SomniaEventHandlerInterface,
} from "../../ReactivityHook.sol/SomniaEventHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "emitter",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "eventTopics",
        type: "bytes32[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onEvent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class SomniaEventHandler__factory {
  static readonly abi = _abi;
  static createInterface(): SomniaEventHandlerInterface {
    return new Interface(_abi) as SomniaEventHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SomniaEventHandler {
    return new Contract(address, _abi, runner) as unknown as SomniaEventHandler;
  }
}
