/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPredictionMarket } from "./IPredictionMarket";
export type { IPriceFeed } from "./IPriceFeed";
export type { ReactivityHook } from "./ReactivityHook";
export type { SomniaEventHandler } from "./SomniaEventHandler";
