/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMarket"
      | "getActiveMarketId"
      | "getMarket"
      | "placeBet"
      | "resolveMarket"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMarketId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
}

export interface IPredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): IPredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: IPredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMarket: TypedContractMethod<
    [
      asset_: string,
      question_: string,
      targetPrice_: BigNumberish,
      createdPrice_: BigNumberish,
      duration_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getActiveMarketId: TypedContractMethod<[asset_: string], [bigint], "view">;

  getMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        asset: string;
        question: string;
        targetPrice: bigint;
        createdPrice: bigint;
        deadline: bigint;
        status: bigint;
        yesPool: bigint;
        noPool: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  placeBet: TypedContractMethod<
    [marketId: BigNumberish, side: BigNumberish],
    [void],
    "payable"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BigNumberish, hitTarget: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      asset_: string,
      question_: string,
      targetPrice_: BigNumberish,
      createdPrice_: BigNumberish,
      duration_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveMarketId"
  ): TypedContractMethod<[asset_: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        asset: string;
        question: string;
        targetPrice: bigint;
        createdPrice: bigint;
        deadline: bigint;
        status: bigint;
        yesPool: bigint;
        noPool: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [marketId: BigNumberish, side: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, hitTarget: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
