/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReactivityHook {
  export type SmartBetStruct = {
    user: AddressLike;
    asset: string;
    isAbove: boolean;
    triggerPrice: BigNumberish;
    side: BigNumberish;
    betAmount: BigNumberish;
    active: boolean;
  };

  export type SmartBetStructOutput = [
    user: string,
    asset: string,
    isAbove: boolean,
    triggerPrice: bigint,
    side: bigint,
    betAmount: bigint,
    active: boolean
  ] & {
    user: string;
    asset: string;
    isAbove: boolean;
    triggerPrice: bigint;
    side: bigint;
    betAmount: bigint;
    active: boolean;
  };
}

export interface ReactivityHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BTC_MILESTONE_STEP"
      | "ETH_MILESTONE_STEP"
      | "MARKET_DURATION"
      | "PRICE_UPDATED_SIG"
      | "SOMI_MILESTONE_STEP"
      | "btcFeed"
      | "cancelSmartBet"
      | "ethFeed"
      | "fund"
      | "getSmartBet"
      | "getUserSmartBets"
      | "lastMilestone"
      | "manualTrigger"
      | "nextSmartBetId"
      | "onEvent"
      | "owner"
      | "predictionMarket"
      | "registerSmartBet"
      | "setFeeds"
      | "smartBets"
      | "somiFeed"
      | "userBalance"
      | "userSmartBets"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Funded"
      | "MarketAutoCreated"
      | "MarketAutoResolved"
      | "SmartBetCancelled"
      | "SmartBetFired"
      | "SmartBetRegistered"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BTC_MILESTONE_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ETH_MILESTONE_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MARKET_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_UPDATED_SIG",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SOMI_MILESTONE_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "btcFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelSmartBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ethFeed", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSmartBet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSmartBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastMilestone",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "manualTrigger",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSmartBetId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictionMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerSmartBet",
    values: [string, boolean, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeds",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "smartBets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "somiFeed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSmartBets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BTC_MILESTONE_STEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ETH_MILESTONE_STEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MARKET_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_UPDATED_SIG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SOMI_MILESTONE_STEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "btcFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelSmartBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ethFeed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSmartBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSmartBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSmartBetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictionMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSmartBet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "smartBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "somiFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userSmartBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace FundedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAutoCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    asset: string,
    targetPrice: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    asset: string,
    targetPrice: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    asset: string;
    targetPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketAutoResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    asset: string,
    hitTarget: boolean
  ];
  export type OutputTuple = [
    marketId: bigint,
    asset: string,
    hitTarget: boolean
  ];
  export interface OutputObject {
    marketId: bigint;
    asset: string;
    hitTarget: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SmartBetCancelledEvent {
  export type InputTuple = [id: BigNumberish, user: AddressLike];
  export type OutputTuple = [id: bigint, user: string];
  export interface OutputObject {
    id: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SmartBetFiredEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    marketId: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, marketId: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    marketId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SmartBetRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    asset: string,
    triggerPrice: BigNumberish,
    side: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    asset: string,
    triggerPrice: bigint,
    side: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    asset: string;
    triggerPrice: bigint;
    side: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReactivityHook extends BaseContract {
  connect(runner?: ContractRunner | null): ReactivityHook;
  waitForDeployment(): Promise<this>;

  interface: ReactivityHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BTC_MILESTONE_STEP: TypedContractMethod<[], [bigint], "view">;

  ETH_MILESTONE_STEP: TypedContractMethod<[], [bigint], "view">;

  MARKET_DURATION: TypedContractMethod<[], [bigint], "view">;

  PRICE_UPDATED_SIG: TypedContractMethod<[], [string], "view">;

  SOMI_MILESTONE_STEP: TypedContractMethod<[], [bigint], "view">;

  btcFeed: TypedContractMethod<[], [string], "view">;

  cancelSmartBet: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  ethFeed: TypedContractMethod<[], [string], "view">;

  fund: TypedContractMethod<[], [void], "payable">;

  getSmartBet: TypedContractMethod<
    [id: BigNumberish],
    [ReactivityHook.SmartBetStructOutput],
    "view"
  >;

  getUserSmartBets: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  lastMilestone: TypedContractMethod<[arg0: string], [bigint], "view">;

  manualTrigger: TypedContractMethod<
    [asset: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextSmartBetId: TypedContractMethod<[], [bigint], "view">;

  onEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  predictionMarket: TypedContractMethod<[], [string], "view">;

  registerSmartBet: TypedContractMethod<
    [
      asset_: string,
      isAbove_: boolean,
      triggerPrice_: BigNumberish,
      side_: BigNumberish,
      betAmount_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setFeeds: TypedContractMethod<
    [eth_: AddressLike, btc_: AddressLike, somi_: AddressLike],
    [void],
    "nonpayable"
  >;

  smartBets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint, boolean] & {
        user: string;
        asset: string;
        isAbove: boolean;
        triggerPrice: bigint;
        side: bigint;
        betAmount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  somiFeed: TypedContractMethod<[], [string], "view">;

  userBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userSmartBets: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BTC_MILESTONE_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH_MILESTONE_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MARKET_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_UPDATED_SIG"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SOMI_MILESTONE_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "btcFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelSmartBet"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getSmartBet"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ReactivityHook.SmartBetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserSmartBets"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "lastMilestone"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualTrigger"
  ): TypedContractMethod<
    [asset: string, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextSmartBetId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "onEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "predictionMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerSmartBet"
  ): TypedContractMethod<
    [
      asset_: string,
      isAbove_: boolean,
      triggerPrice_: BigNumberish,
      side_: BigNumberish,
      betAmount_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeds"
  ): TypedContractMethod<
    [eth_: AddressLike, btc_: AddressLike, somi_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "smartBets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, bigint, bigint, boolean] & {
        user: string;
        asset: string;
        isAbove: boolean;
        triggerPrice: bigint;
        side: bigint;
        betAmount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "somiFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userSmartBets"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "MarketAutoCreated"
  ): TypedContractEvent<
    MarketAutoCreatedEvent.InputTuple,
    MarketAutoCreatedEvent.OutputTuple,
    MarketAutoCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketAutoResolved"
  ): TypedContractEvent<
    MarketAutoResolvedEvent.InputTuple,
    MarketAutoResolvedEvent.OutputTuple,
    MarketAutoResolvedEvent.OutputObject
  >;
  getEvent(
    key: "SmartBetCancelled"
  ): TypedContractEvent<
    SmartBetCancelledEvent.InputTuple,
    SmartBetCancelledEvent.OutputTuple,
    SmartBetCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SmartBetFired"
  ): TypedContractEvent<
    SmartBetFiredEvent.InputTuple,
    SmartBetFiredEvent.OutputTuple,
    SmartBetFiredEvent.OutputObject
  >;
  getEvent(
    key: "SmartBetRegistered"
  ): TypedContractEvent<
    SmartBetRegisteredEvent.InputTuple,
    SmartBetRegisteredEvent.OutputTuple,
    SmartBetRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Funded(address,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "MarketAutoCreated(uint256,string,uint256)": TypedContractEvent<
      MarketAutoCreatedEvent.InputTuple,
      MarketAutoCreatedEvent.OutputTuple,
      MarketAutoCreatedEvent.OutputObject
    >;
    MarketAutoCreated: TypedContractEvent<
      MarketAutoCreatedEvent.InputTuple,
      MarketAutoCreatedEvent.OutputTuple,
      MarketAutoCreatedEvent.OutputObject
    >;

    "MarketAutoResolved(uint256,string,bool)": TypedContractEvent<
      MarketAutoResolvedEvent.InputTuple,
      MarketAutoResolvedEvent.OutputTuple,
      MarketAutoResolvedEvent.OutputObject
    >;
    MarketAutoResolved: TypedContractEvent<
      MarketAutoResolvedEvent.InputTuple,
      MarketAutoResolvedEvent.OutputTuple,
      MarketAutoResolvedEvent.OutputObject
    >;

    "SmartBetCancelled(uint256,address)": TypedContractEvent<
      SmartBetCancelledEvent.InputTuple,
      SmartBetCancelledEvent.OutputTuple,
      SmartBetCancelledEvent.OutputObject
    >;
    SmartBetCancelled: TypedContractEvent<
      SmartBetCancelledEvent.InputTuple,
      SmartBetCancelledEvent.OutputTuple,
      SmartBetCancelledEvent.OutputObject
    >;

    "SmartBetFired(uint256,address,uint256)": TypedContractEvent<
      SmartBetFiredEvent.InputTuple,
      SmartBetFiredEvent.OutputTuple,
      SmartBetFiredEvent.OutputObject
    >;
    SmartBetFired: TypedContractEvent<
      SmartBetFiredEvent.InputTuple,
      SmartBetFiredEvent.OutputTuple,
      SmartBetFiredEvent.OutputObject
    >;

    "SmartBetRegistered(uint256,address,string,uint256,uint8,uint256)": TypedContractEvent<
      SmartBetRegisteredEvent.InputTuple,
      SmartBetRegisteredEvent.OutputTuple,
      SmartBetRegisteredEvent.OutputObject
    >;
    SmartBetRegistered: TypedContractEvent<
      SmartBetRegisteredEvent.InputTuple,
      SmartBetRegisteredEvent.OutputTuple,
      SmartBetRegisteredEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
