/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "PredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PredictionMarket__factory>;
    getContractFactory(
      name: "PriceFeed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PriceFeed__factory>;
    getContractFactory(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPredictionMarket__factory>;
    getContractFactory(
      name: "ReactivityHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReactivityHook__factory>;
    getContractFactory(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SomniaEventHandler__factory>;

    getContractAt(
      name: "PredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PredictionMarket>;
    getContractAt(
      name: "PriceFeed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PriceFeed>;
    getContractAt(
      name: "IPredictionMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPredictionMarket>;
    getContractAt(
      name: "ReactivityHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReactivityHook>;
    getContractAt(
      name: "SomniaEventHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SomniaEventHandler>;

    deployContract(
      name: "PredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarket>;
    deployContract(
      name: "PriceFeed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeed>;
    deployContract(
      name: "IPredictionMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "ReactivityHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReactivityHook>;
    deployContract(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;

    deployContract(
      name: "PredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PredictionMarket>;
    deployContract(
      name: "PriceFeed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PriceFeed>;
    deployContract(
      name: "IPredictionMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPredictionMarket>;
    deployContract(
      name: "ReactivityHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReactivityHook>;
    deployContract(
      name: "SomniaEventHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
