/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PredictionMarket {
  export type MarketStruct = {
    id: BigNumberish;
    asset: string;
    question: string;
    targetPrice: BigNumberish;
    createdPrice: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    yesPool: BigNumberish;
    noPool: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type MarketStructOutput = [
    id: bigint,
    asset: string,
    question: string,
    targetPrice: bigint,
    createdPrice: bigint,
    deadline: bigint,
    status: bigint,
    yesPool: bigint,
    noPool: bigint,
    resolvedAt: bigint
  ] & {
    id: bigint;
    asset: string;
    question: string;
    targetPrice: bigint;
    createdPrice: bigint;
    deadline: bigint;
    status: bigint;
    yesPool: bigint;
    noPool: bigint;
    resolvedAt: bigint;
  };

  export type BetStruct = {
    side: BigNumberish;
    amount: BigNumberish;
    claimed: boolean;
  };

  export type BetStructOutput = [
    side: bigint,
    amount: bigint,
    claimed: boolean
  ] & { side: bigint; amount: bigint; claimed: boolean };
}

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_BET"
      | "activeMarketByAsset"
      | "bets"
      | "claimPayout"
      | "createMarket"
      | "getActiveMarketId"
      | "getMarket"
      | "getTotalPool"
      | "getUserBet"
      | "hook"
      | "markets"
      | "nextMarketId"
      | "owner"
      | "placeBet"
      | "resolveMarket"
      | "setHook"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "MarketCreated"
      | "MarketResolved"
      | "PayoutClaimed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeMarketByAsset",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "bets",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMarketId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "hook", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setHook",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeMarketByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setHook", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    bettor: AddressLike,
    side: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    bettor: string,
    side: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    bettor: string;
    side: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    asset: string,
    question: string,
    targetPrice: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    asset: string,
    question: string,
    targetPrice: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    asset: string;
    question: string;
    targetPrice: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    asset: string,
    result: BigNumberish,
    yesPool: BigNumberish,
    noPool: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    asset: string,
    result: bigint,
    yesPool: bigint,
    noPool: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    asset: string;
    result: bigint;
    yesPool: bigint;
    noPool: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayoutClaimedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    bettor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [marketId: bigint, bettor: string, amount: bigint];
  export interface OutputObject {
    marketId: bigint;
    bettor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  activeMarketByAsset: TypedContractMethod<[arg0: string], [bigint], "view">;

  bets: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        side: bigint;
        amount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  claimPayout: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createMarket: TypedContractMethod<
    [
      asset_: string,
      question_: string,
      targetPrice_: BigNumberish,
      createdPrice_: BigNumberish,
      duration_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getActiveMarketId: TypedContractMethod<[asset_: string], [bigint], "view">;

  getMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;

  getTotalPool: TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;

  getUserBet: TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [PredictionMarket.BetStructOutput],
    "view"
  >;

  hook: TypedContractMethod<[], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        asset: string;
        question: string;
        targetPrice: bigint;
        createdPrice: bigint;
        deadline: bigint;
        status: bigint;
        yesPool: bigint;
        noPool: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [marketId: BigNumberish, side: BigNumberish],
    [void],
    "payable"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BigNumberish, hitTarget: boolean],
    [void],
    "nonpayable"
  >;

  setHook: TypedContractMethod<[hook_: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeMarketByAsset"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "bets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        side: bigint;
        amount: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimPayout"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      asset_: string,
      question_: string,
      targetPrice_: BigNumberish,
      createdPrice_: BigNumberish,
      duration_: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveMarketId"
  ): TypedContractMethod<[asset_: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [PredictionMarket.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPool"
  ): TypedContractMethod<[marketId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [marketId: BigNumberish, user: AddressLike],
    [PredictionMarket.BetStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        asset: string;
        question: string;
        targetPrice: bigint;
        createdPrice: bigint;
        deadline: bigint;
        status: bigint;
        yesPool: bigint;
        noPool: bigint;
        resolvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [marketId: BigNumberish, side: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, hitTarget: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHook"
  ): TypedContractMethod<[hook_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "PayoutClaimed"
  ): TypedContractEvent<
    PayoutClaimedEvent.InputTuple,
    PayoutClaimedEvent.OutputTuple,
    PayoutClaimedEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,uint8,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "MarketCreated(uint256,string,string,uint256,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,string,uint8,uint256,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "PayoutClaimed(uint256,address,uint256)": TypedContractEvent<
      PayoutClaimedEvent.InputTuple,
      PayoutClaimedEvent.OutputTuple,
      PayoutClaimedEvent.OutputObject
    >;
    PayoutClaimed: TypedContractEvent<
      PayoutClaimedEvent.InputTuple,
      PayoutClaimedEvent.OutputTuple,
      PayoutClaimedEvent.OutputObject
    >;
  };
}
